PRAGMA foreign_keys = 1;
BEGIN TRANSACTION;
CREATE TABLE users (
	id INTEGER PRIMARY KEY NOT NULL,
	email TEXT UNIQUE NOT NULL,
	name TEXT NOT NULL,
	handle TEXT UNIQUE NOT NULL
);
CREATE UNIQUE INDEX handleindex on users(handle);
CREATE TABLE scores (
	userid INTEGER NOT NULL PRIMARY KEY,
	score INTEGER NOT NULL,
	FOREIGN KEY(userid) REFERENCES users(id)
);
CREATE TABLE sessions (
	sessionid TEXT UNIQUE NOT NULL,
	userid INTEGER UNIQUE NOT NULL,
	FOREIGN KEY(userid) REFERENCES users(id)
);
CREATE UNIQUE INDEX sidindex on sessions(sessionid);
CREATE TABLE claimed (
	userid INTEGER NOT NULL,
	code TEXT NOT NULL,
	FOREIGN KEY(userid) REFERENCES users(id)
);
CREATE TABLE attempts (
	userid INTEGER NOT NULL PRIMARY KEY,
	lastattempt INTEGER UNIQUE NOT NULL,
	FOREIGN KEY(userid) REFERENCES users(id)
);
COMMIT;
